### ISSUE TITLE
Write helper functions for collecting responses

### ISSUE THREAD

**Issue by sspathak** [david-fisher/320-F20-Track-II#146]
funcitons for creating/updating submission row, response row.

- [ ] use helper functions in 

- [ ] addInitialReflectionResponse()

- [ ] addMiddleReflectionResponse()

- [ ] addFinalReflectionResponse()

**Comment by rlee287** [comment]
Possibly addressed in commit 96e4f6eee50e55b0b8e5b7652187269590c1a137, and maybe closable after being merged into `differential_team`.
