### ISSUE TITLE
Create ER diagram for database schema

### ISSUE THREAD

**Issue by sspathak** [david-fisher/320-F20-Track-II#39]
- [x] Add 'users' table to ERD
- [x] Add 'students' table to ERD
- [x] Add 'instructors' table to ERD
- [x] Add 'courses table to ERD
- [x] Add 'scenarios' table to ERD
- [x] Add 'stakeholders table to ERD
- [x] Add tables for pages to ERD
- [x] Add MCQ questions and options tables to ERD
- [x] Add MCQ responses table to ERD
- [x] Add stakeholder choices table to ERD

**Comment by rlee287** [comment]
Crossref #124: initial SQL file based on diagram merged in, but this will continue to be developed as necessary.
